import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NextAuthProvider from "@/providers/NextAuthProvider";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata = {
  title: "Glow Pure",
  description: "Generated by Abdul Aziz Shishir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextAuthProvider>
          <Navbar />
          {children}
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
