import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { AppThemeProvider } from "@/components/ThemeProvider";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata = {
  title: "Glow Pure",
  description: "Generated by Abdul Aziz Shishir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <AppThemeProvider>
          <NextAuthProvider>
            <Navbar />
            {children}
            <Footer />
          </NextAuthProvider>
        </AppThemeProvider>
      </body>
    </html>
  );
}
